version: "3.6"

services:
  postgres:
    restart: on-failure
    image: "postgres:9.6.6"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: "${PGDATA_LOCATION}"
    ports:
      - "${POSTGRES_PORT}:5432"

  inventory_api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    restart: "no"
    env_file:
      - .env
    environment:
      LOGGER_SERVICE_NAME: inventory_api
    command: --api
    ports:
      - "${INVENTORY_API_PORT}:${INVENTORY_API_PORT}"
    depends_on:
      - postgres

  db_migrations:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    restart: on-failure
    env_file:
      - .env
    environment:
      LOGGER_SERVICE_NAME: migrations
    depends_on:
      - postgres
    command: --migrations

  tests:
    build:
      context: ../
      dockerfile: docker/tests.Dockerfile
    env_file:
     - .env
    environment:
      LOGGER_SERVICE_NAME: tests
      FLASK_APP: api/inventory_api/app
    depends_on:
      - inventory_api
      - postgres
